#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QMainWindow>
#include "secondwindow.h"  // Include the header for the SecondWindow class

//contain user interface element generated by qt designer
QT_BEGIN_NAMESPACE
namespace Ui { class MainWindow; }
QT_END_NAMESPACE

// The MainWindow class is derived from QMainWindow and represents the main application window.
class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    // Constructor for MainWindow. Optionally takes a parent widget.
    MainWindow(QWidget *parent = nullptr);
    // Destructor for MainWindow. Cleans up resources.
    ~MainWindow();

private slots:

    void on_nextButton_clicked();//This is a slot function that will be called when the "Next" button is clicked

private:
    // Pointer to the UI elements managed by the Qt Designer.
    Ui::MainWindow *ui;
    // Pointer to an instance of the SecondWindow class.
    SecondWindow *secondWindow;
};

#endif // MAINWINDOW_H
